
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 131
#define YY_END_OF_BUFFER 132
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[535] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  132,  130,  129,  130,  130,  128,  128,  128,
      128,  128,  128,  128,  128,  128,    4,    3,    4,   56,
       54,   55,   36,   42,   35,   56,   53,   52,   40,   39,
       49,   38,   56,   41,   28,   28,   56,   47,   43,   48,
       44,   25,   25,   33,   34,   45,   25,   25,   25,   25,
       25,   25,   25,   25,   50,   46,   51,   37,    7,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   10,    9,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,  122,  120,  121,  106,

      122,  112,  105,  122,  100,  101,  110,  109,   97,  108,
      104,  111,   67,   67,   98,   94,  113,   99,  114,  117,
       64,   64,  102,  103,  115,   64,   64,   64,   64,   64,
       64,   64,   64,   95,  116,   96,  107,    0,    0,    0,
        0,  123,  124,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,    2,    0,    0,   31,   23,
       24,   32,   27,    0,   28,    0,   28,   34,   33,   25,
        0,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,    5,    8,   93,    0,   72,    0,   79,   96,
       88,   80,    0,    0,    0,    0,    0,    0,    0,    0,

       77,   85,   75,   86,   76,   87,   70,   57,  119,   78,
       71,   66,    0,   67,    0,   67,  103,   95,  102,   84,
       90,   92,   91,   83,   64,    0,    0,   81,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       82,   89,    0,    0,    0,  124,  124,  128,  128,  128,
      128,   15,  128,  128,  128,  128,  128,  128,  128,   29,
        0,   31,   24,   24,   31,    0,   32,   27,    0,   30,
       26,   25,   25,   25,   25,   15,   25,   25,   25,   25,
       25,   25,   25,   68,    0,    0,    0,    0,    0,    0,
       70,  119,  119,   70,    0,   71,   66,    0,   69,   65,

       74,   73,   64,   64,   64,   64,   58,   15,   64,   64,
       64,   64,   64,   64,   64,    0,    0,    0,  124,   11,
      128,  128,  128,   16,  128,  128,  128,  128,   21,  128,
        0,   31,   24,    0,   31,    0,   32,   30,   26,   11,
       25,   25,   25,   16,   25,   25,   25,   25,   21,   25,
        0,    0,    0,    0,    0,    0,   70,  119,    0,   70,
        0,   71,   69,   65,   11,   64,   64,   64,   16,   64,
       64,   64,   64,   21,   64,    0,    0,    0,  127,  124,
       12,  128,   14,   17,  128,  128,  128,  128,   24,    0,
       31,   12,   25,   14,   17,   25,   25,   25,   25,    0,

        0,    0,    0,   60,    0,  119,    0,   70,   12,   64,
       14,   17,   64,   64,   64,   64,    0,    0,  124,   13,
       18,   19,  128,  128,   24,   13,   18,   19,   25,   25,
        0,   59,    0,    0,    0,   63,  119,   13,   18,   19,
       64,   64,    0,    0,  126,  124,  128,  128,   24,   25,
       25,    0,    0,   61,  119,   64,   64,    0,  125,  124,
       20,   22,   24,   20,   22,    0,   62,  119,   20,   22,
      124,   24,  119,  124,   24,  119,  124,   24,  119,  124,
       24,  119,  124,   24,  119,  124,   24,  119,  124,   24,
      119,  124,   24,  119,  124,   24,  119,  124,   24,  119,

      124,   24,  119,  124,   24,  119,  124,   24,  119,  124,
       24,  119,  124,   24,  119,  124,   24,  119,  119,  124,
       24,  119,  119,  124,   24,  118,  119,  124,   24,  119,
        1,    1,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   29,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   35,   32,   36,
       32,   37,   38,   39,   40,   32,   32,   41,   32,   42,
       43,   44,   45,   46,   32,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   32,   32,   56,   32,   57,
       58,   32,   32,   59,   60,   61,   62,   63,   32,   41,
       32,   32,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[547] =
    {   0,
        0,    0,   65,   66,   78,    0,  145,    0,  212,    0,
      279,    0, 1067, 1068, 1068,  345,   58,    0,   18, 1008,
     1009, 1007, 1005,  296, 1005, 1003, 1068, 1068, 1043, 1068,
     1068, 1068, 1068, 1068, 1068, 1015,  351, 1068, 1068, 1068,
     1068, 1068,   55,  342,  342,  351, 1034, 1068, 1037, 1068,
     1068,    0, 1047, 1068, 1068, 1068,  294,  997,  998,  996,
      994,  310,  994,  992, 1068, 1068, 1068, 1068, 1068, 1068,
      364, 1032,  361,    0,  321,  990,  991,  989,  987,  333,
      987,  985, 1068, 1068,  382, 1025,  393,    0,  338,  983,
      984,  982,  980,  354,  980,  978, 1068, 1068, 1068, 1012,

      368,  339,  403,  990,  416, 1068, 1010,  367, 1068,  406,
      404,  416,  422,  430, 1008, 1068,  435, 1008,  401, 1068,
        0,  438, 1068, 1068, 1007,  373,  971,  387,  971,  969,
      421,  969,  967, 1068,  394, 1068, 1068,  449,  966,  967,
      965, 1068, 1017,    0,  973,  962,  956,  959,  955,  958,
      956,  960,  965,  951,  380, 1068,  441,  458,  472, 1068,
     1006,  478,  497,  492,  480,    0,  522, 1068, 1068,    0,
      965,  961,  950,  944,  947,  943,  946,  944,  948,  953,
      939,  432, 1068, 1068, 1068,  474, 1068,  995, 1068, 1068,
     1068, 1068,  445,  474,  517,  943,  938,  939,  937,  935,

     1068, 1068, 1068, 1068, 1068, 1068,  545, 1068,  988, 1068,
      552,  572,  531,  499,    0,  591, 1068, 1068, 1068,  968,
     1068, 1068, 1068,  967,    0,  488,  945, 1068,  941,  930,
      924,  927,  925,  922,  925,  923,  927,  932,  918,  470,
     1068, 1068,  915,  918,  914,    0,  938,  914,  912,  923,
      923,    0,  916,  909,  910,  905,  910,  914,  916, 1068,
      574, 1068,    0,  926,  599,  601, 1068,  592,  539,  618,
      601,  902,  900,  911,  911,    0,  904,  897,  898,  893,
      898,  902,  904, 1068,  903,  887,  890,  886,  891,  625,
     1068,    0,  909,  641,  643, 1068,  633,  576,  646,  644,

     1068, 1068,  885,  883,  894,  894,    0,    0,  887,  880,
      881,  876,  881,  885,  887,  885,  885,  543,  905,    0,
      869,  873,  867,    0,  866,  875,  870,  871,    0,  862,
      580,  685,  896,  668, 1068,  627,  690, 1068,  645,    0,
      860,  864,  858,    0,  857,  866,  861,  862,    0,  853,
      854,  864,  864,  611,  860,  650,  692,  883,  699, 1068,
      672,  709, 1068,  691,    0,  847,  851,  845,    0,  844,
      853,  848,  849,    0,  840,  844,  838,  711, 1068,  861,
        0,  846,    0,    0,  846,  846,  837,  838,  855,  711,
      720,    0,  840,    0,    0,  840,  840,  831,  832,  748,

      830,  824,  753, 1068,  756,  847,  714,  744,    0,  832,
        0,    0,  832,  832,  823,  824,  827,  766,  851,    0,
        0,    0,  825,  819,  848,    0,    0,    0,  822,  816,
      769, 1068,  820,  777,  780, 1068,  844,    0,    0,    0,
      818,  812,  781,  791, 1068,  833,  816,  814,  830,  813,
      811,  795,  799, 1068,  827,  810,  805,  803, 1068,  817,
        0,    0,  812,    0,    0,  807, 1068,  806,    0,    0,
      798,  787,  786,  781,  779,  778,  775,  771,  765,  752,
      748,  747,  757,  756,  744,  765,  762,  752,  716,  712,
      703,  700,  699,  685,  701,  695,  692,  666,  660,  654,

      636,  626,  599,  598,  595,  582,  579,  574,  559,  577,
      573,  570,  530,  527,  505,  521,  512,  487,  478,  474,
      472,  466,  467,  437,  435,    0,  432,  360,  350,  338,
        0,    0,    0, 1068,  818,  820,  825,  827,  832,  837,
      839,  844,  849,  352,  854,   67
    } ;

static yyconst flex_int16_t yy_def[547] =
    {   0,
      534,    1,  535,  535,  534,    5,  534,    7,  534,    9,
      534,   11,  534,  534,  534,  534,  534,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  537,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  538,  538,  534,  534,  534,  538,  538,  538,  538,
      538,  538,  538,  538,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  534,  534,  534,  534,  534,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  534,  534,  534,  534,

      539,  534,  534,  540,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      541,  541,  534,  534,  534,  541,  541,  541,  541,  541,
      541,  541,  541,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  542,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  534,  537,  537,  534,  534,
      543,  534,  534,  534,  534,  544,  534,  534,  534,  538,
      537,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  534,  534,  534,  539,  534,  539,  534,  534,
      534,  534,  540,  540,  534,  534,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  545,  534,
      534,  534,  534,  534,  546,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  541,  539,  540,  534,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      534,  534,  534,  534,  534,  542,  542,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  534,
      534,  534,  543,  543,  534,  534,  534,  534,  534,  534,
      544,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  534,  534,  534,  534,  534,  534,  534,
      534,  545,  545,  534,  534,  534,  534,  534,  534,  546,

      534,  534,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  534,  534,  534,  542,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      534,  534,  543,  534,  534,  534,  534,  534,  534,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      534,  534,  534,  534,  534,  534,  534,  545,  534,  534,
      534,  534,  534,  534,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  534,  534,  534,  534,  542,
      536,  536,  536,  536,  536,  536,  536,  536,  543,  534,
      534,  538,  538,  538,  538,  538,  538,  538,  538,  534,

      534,  534,  534,  534,  534,  545,  534,  534,  541,  541,
      541,  541,  541,  541,  541,  541,  534,  534,  542,  536,
      536,  536,  536,  536,  543,  538,  538,  538,  538,  538,
      534,  534,  534,  534,  534,  534,  545,  541,  541,  541,
      541,  541,  534,  534,  534,  542,  536,  536,  543,  538,
      538,  534,  534,  534,  545,  541,  541,  534,  534,  542,
      536,  536,  543,  538,  538,  534,  534,  545,  541,  541,
      542,  543,  545,  542,  543,  545,  542,  543,  545,  542,
      543,  545,  542,  543,  545,  542,  543,  545,  542,  543,
      545,  542,  543,  545,  542,  543,  545,  542,  543,  545,

      542,  543,  545,  542,  543,  545,  542,  543,  545,  542,
      543,  545,  542,  543,  545,  542,  543,  545,  545,  542,
      543,  545,  545,  542,  543,  545,  545,  542,  543,  545,
      542,  543,  545,    0,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534
    } ;

static yyconst flex_int16_t yy_nxt[1136] =
    {   0,
       14,   14,   15,   14,   14,   14,   14,   14,   14,   16,
       14,   14,   14,   14,   14,   14,   17,   14,   14,   14,
       14,   14,   14,   14,   14,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   14,   14,   14,   14,   18,   18,   19,   20,
       18,   21,   18,   18,   22,   23,   18,   18,   18,   24,
       18,   25,   26,   14,   14,   14,   14,   28,   28,  142,
      300,  145,  159,  159,  143,  146,   29,   29,   30,   31,
       32,   31,   33,   30,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,

       50,   51,   30,   52,   52,   52,   52,   52,   52,   52,
       52,   53,   52,   52,   52,   52,   52,   52,   52,   52,
       54,   30,   55,   56,   52,   52,   57,   58,   52,   59,
       52,   52,   60,   61,   52,   52,   52,   62,   52,   63,
       64,   65,   66,   67,   68,   69,   69,   70,   69,   69,
       69,   69,   69,   69,   71,   69,   72,   69,   69,   69,
       69,   73,   69,   69,   69,   69,   69,   69,   69,   69,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   69,   69,   69,
       69,   74,   74,   75,   76,   74,   77,   74,   74,   78,

       79,   74,   74,   74,   80,   74,   81,   82,   69,   69,
       69,   69,   83,   83,   84,   83,   83,   83,   83,   83,
       83,   85,   83,   86,   83,   83,   83,   83,   87,   83,
       83,   83,   83,   83,   83,   83,   83,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   83,   83,   83,   83,   88,   88,
       89,   90,   88,   91,   88,   88,   92,   93,   88,   88,
       88,   94,   88,   95,   96,   83,   83,   83,   83,   97,
       98,   99,   98,  100,  101,  102,  103,  104,  105,  106,
      107,  108,  109,  110,  111,  112,  113,  114,  115,  116,

      117,  118,  119,  120,  121,  121,  121,  121,  121,  121,
      121,  121,  122,  121,  121,  121,  121,  121,  121,  121,
      121,  123,   97,  124,  125,  121,  121,  126,  127,  121,
      128,  121,  121,  129,  130,  121,  121,  121,  131,  121,
      132,  133,  134,  135,  136,  137,  138,  172,  138,  151,
      152,  173,  138,  160,  138,  271,  153,  162,  161,  163,
      163,  189,  190,  178,  179,  138,  162,  138,  167,  167,
      180,  164,  142,  187,  145,  165,  533,  143,  146,  202,
      164,  165,  166,  138,  165,  138,  151,  152,  532,  203,
      165,  145,  164,  153,  139,  146,  140,  165,  531,  141,

      139,  164,  140,  165,  142,  141,  165,  151,  152,  143,
      191,  188,  165,  139,  153,  140,  241,  195,  141,  195,
      204,  207,  207,  223,  224,  192,  229,  208,  205,  206,
      230,  139,  209,  140,  258,  259,  141,  211,  210,  212,
      212,  218,  232,  226,  233,  211,  227,  216,  216,  260,
      138,  213,  138,  284,  219,  214,  220,  221,  242,  213,
      534,  214,  215,  214,  196,  197,  157,  198,  530,  214,
      199,  529,  213,  528,  236,  237,  534,  214,  200,  187,
      213,  238,  193,  214,  158,  214,  282,  283,  194,  159,
      159,  214,  527,  187,  526,  265,  265,  525,  139,  524,

      140,  261,  262,  141,  269,  262,  269,  266,  267,  270,
      270,  267,  162,  165,  163,  163,  523,  188,  195,  165,
      195,  522,  261,  262,  314,  315,  164,  262,  266,  267,
      268,  188,  214,  267,  518,  165,  268,  162,  214,  167,
      167,  165,  519,  298,  378,  298,  378,  164,  299,  299,
      521,  164,  268,  379,  214,  165,  270,  270,  268,  520,
      214,  165,  207,  207,  517,  196,  197,  516,  198,  294,
      294,  199,  164,  515,  290,  291,  514,  165,  291,  200,
      513,  295,  296,  165,  512,  296,  331,  211,  331,  212,
      212,  332,  332,  299,  299,  290,  291,  332,  332,  511,

      291,  213,  295,  296,  510,  297,  211,  296,  216,  216,
      509,  297,  403,  336,  403,  336,  265,  265,  337,  337,
      213,  404,  213,  508,  214,  268,  507,  297,  334,  335,
      214,  268,  335,  297,  339,  270,  270,  356,  506,  356,
      339,  213,  357,  357,  337,  337,  214,  268,  338,  334,
      335,  338,  214,  268,  335,  361,  339,  361,  294,  294,
      362,  362,  339,  299,  299,  505,  297,  357,  357,  338,
      359,  360,  297,  338,  360,  504,  363,  364,  339,  363,
      390,  503,  390,  364,  339,  391,  391,  502,  297,  362,
      362,  359,  360,  501,  297,  500,  360,  363,  499,  364,

      339,  363,  332,  332,  498,  364,  339,  337,  337,  357,
      357,  407,  378,  407,  378,  262,  408,  408,  262,  497,
      267,  379,  291,  267,  364,  291,  362,  362,  391,  391,
      364,  408,  408,  496,  495,  494,  262,  391,  391,  296,
      262,  267,  296,  291,  493,  267,  364,  291,  492,  431,
      335,  431,  364,  335,  403,  491,  403,  435,  432,  435,
      296,  408,  408,  404,  296,  490,  436,  444,  489,  444,
      431,  335,  431,  488,  360,  335,  445,  360,  453,  432,
      453,  435,  458,  435,  458,  487,  486,  454,  485,  484,
      436,  459,  444,  483,  444,  360,  466,  482,  466,  360,

      453,  445,  453,  481,  458,  467,  458,  480,  466,  454,
      466,  479,  478,  459,  477,  476,  475,  467,   27,   27,
       27,   27,   27,  144,  144,  157,  157,  474,  157,  157,
      170,  170,  186,  186,  186,  186,  186,  193,  193,  473,
      193,  193,  225,  225,  246,  472,  246,  246,  246,  263,
      471,  263,  263,  263,  292,  470,  292,  292,  292,  469,
      468,  465,  464,  463,  462,  461,  460,  457,  456,  455,
      452,  451,  450,  449,  448,  447,  446,  443,  442,  441,
      440,  439,  438,  437,  434,  433,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,

      416,  415,  414,  413,  412,  411,  410,  409,  406,  405,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  365,  358,  355,  354,  353,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  333,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  194,  302,
      301,  293,  289,  288,  287,  286,  285,  534,  281,  280,

      279,  278,  277,  276,  275,  274,  273,  272,  158,  264,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  245,  244,  243,  240,  239,  235,  234,  231,  228,
      222,  217,  201,  194,  185,  155,  154,  150,  149,  148,
      147,  184,  155,  154,  150,  149,  148,  147,  183,  182,
      181,  177,  176,  175,  174,  171,  169,  168,  158,  156,
      155,  154,  150,  149,  148,  147,  534,   13,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534
    } ;

static yyconst flex_int16_t yy_chk[1136] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,   17,
      546,   19,   43,   43,   17,   19,    3,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   16,   57,   16,   24,
       24,   57,   37,   44,   37,  544,   24,   45,   44,   45,
       45,  102,  102,   62,   62,   71,   46,   71,   46,   46,
       62,   45,   73,  101,   75,   45,  530,   73,   75,  108,
       46,   45,   45,   85,   46,   85,   80,   80,  529,  108,
       46,   89,   45,   80,   16,   89,   16,   45,  528,   16,

       37,   46,   37,   45,   87,   37,   46,   94,   94,   87,
      103,  101,   46,   71,   94,   71,  135,  105,   71,  105,
      110,  111,  111,  119,  119,  103,  126,  112,  110,  110,
      126,   85,  112,   85,  155,  155,   85,  113,  112,  113,
      113,  117,  128,  122,  128,  114,  122,  114,  114,  157,
      138,  113,  138,  193,  117,  113,  117,  117,  135,  114,
      158,  113,  113,  114,  105,  105,  158,  105,  527,  114,
      105,  525,  113,  524,  131,  131,  194,  113,  105,  186,
      114,  131,  194,  113,  157,  114,  182,  182,  193,  159,
      159,  114,  523,  226,  522,  162,  162,  521,  138,  520,

      138,  159,  159,  138,  164,  159,  164,  162,  162,  164,
      164,  162,  163,  165,  163,  163,  519,  186,  195,  165,
      195,  518,  159,  159,  240,  240,  163,  159,  162,  162,
      163,  226,  214,  162,  515,  165,  163,  167,  214,  167,
      167,  165,  515,  213,  318,  213,  318,  163,  213,  213,
      517,  167,  163,  318,  214,  167,  269,  269,  163,  516,
      214,  167,  207,  207,  514,  195,  195,  513,  195,  211,
      211,  195,  167,  512,  207,  207,  511,  167,  207,  195,
      510,  211,  211,  167,  509,  211,  261,  212,  261,  212,
      212,  261,  261,  298,  298,  207,  207,  331,  331,  508,

      207,  212,  211,  211,  507,  212,  216,  211,  216,  216,
      506,  212,  354,  266,  354,  266,  265,  265,  266,  266,
      216,  354,  212,  505,  216,  268,  504,  212,  265,  265,
      216,  268,  265,  212,  271,  270,  270,  290,  503,  290,
      271,  216,  290,  290,  336,  336,  216,  268,  270,  265,
      265,  270,  216,  268,  265,  295,  271,  295,  294,  294,
      295,  295,  271,  299,  299,  502,  297,  356,  356,  270,
      294,  294,  297,  270,  294,  501,  299,  300,  339,  299,
      334,  500,  334,  300,  339,  334,  334,  499,  297,  361,
      361,  294,  294,  498,  297,  497,  294,  299,  496,  300,

      339,  299,  332,  332,  495,  300,  339,  337,  337,  357,
      357,  359,  378,  359,  378,  332,  359,  359,  332,  494,
      337,  378,  357,  337,  364,  357,  362,  362,  390,  390,
      364,  407,  407,  493,  492,  491,  332,  391,  391,  362,
      332,  337,  362,  357,  490,  337,  364,  357,  489,  400,
      391,  400,  364,  391,  403,  488,  403,  405,  400,  405,
      362,  408,  408,  403,  362,  487,  405,  418,  486,  418,
      431,  391,  431,  485,  408,  391,  418,  408,  434,  431,
      434,  435,  443,  435,  443,  484,  483,  434,  482,  481,
      435,  443,  444,  480,  444,  408,  452,  479,  452,  408,

      453,  444,  453,  478,  458,  452,  458,  477,  466,  453,
      466,  476,  475,  458,  474,  473,  472,  466,  535,  535,
      535,  535,  535,  536,  536,  537,  537,  471,  537,  537,
      538,  538,  539,  539,  539,  539,  539,  540,  540,  468,
      540,  540,  541,  541,  542,  463,  542,  542,  542,  543,
      460,  543,  543,  543,  545,  457,  545,  545,  545,  456,
      455,  451,  450,  449,  448,  447,  446,  442,  441,  437,
      433,  430,  429,  425,  424,  423,  419,  417,  416,  415,
      414,  413,  410,  406,  402,  401,  399,  398,  397,  396,
      393,  389,  388,  387,  386,  385,  382,  380,  377,  376,

      375,  373,  372,  371,  370,  368,  367,  366,  358,  355,
      353,  352,  351,  350,  348,  347,  346,  345,  343,  342,
      341,  333,  330,  328,  327,  326,  325,  323,  322,  321,
      319,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      306,  305,  304,  303,  293,  289,  288,  287,  286,  285,
      283,  282,  281,  280,  279,  278,  277,  275,  274,  273,
      272,  264,  259,  258,  257,  256,  255,  254,  253,  251,
      250,  249,  248,  247,  245,  244,  243,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  227,  224,
      220,  209,  200,  199,  198,  197,  196,  188,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  171,  161,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      143,  141,  140,  139,  133,  132,  130,  129,  127,  125,
      118,  115,  107,  104,  100,   96,   95,   93,   92,   91,
       90,   86,   82,   81,   79,   78,   77,   76,   72,   64,
       63,   61,   60,   59,   58,   53,   49,   47,   36,   29,
       26,   25,   23,   22,   21,   20,   13,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/ansiC.l"
#line 2 "src/ansiC.l"
/************************************************
* ANJANA SINGH
* Y8127079
* DEPARTMENT OF COMPUTER SCIENCE AND ENGINNERING
* IIT KANPUR
*
* C LEXICAL ANALYSIS
* LEXEMES ARE ONLY FOR RELEVENT
* WORKING
************************************************/

#include <stdlib.h>
#include <stdio.h>
void yyerror(char *);
#include "y.tab.h"
#include<string.h>
#include<math.h>
int count_bracket;
extern int yylex();





#line 913 "lex.yy.c"

#define INITIAL 0
#define CMNT 1
#define DEF 2
#define DEF_CMNT 3
#define LOOP_CMNT 4
#define LOOP 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 39 "src/ansiC.l"


#line 1108 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 535 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1068 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "src/ansiC.l"
{BEGIN(LOOP); start_num = line_num; printf("PARALLEL_START "); return(PARALLEL_START);}
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 44 "src/ansiC.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 45 "src/ansiC.l"
{line_num++;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "src/ansiC.l"
; 
	YY_BREAK


case 5:
YY_RULE_SETUP
#line 50 "src/ansiC.l"
{BEGIN(DEF);}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 51 "src/ansiC.l"
{line_num++;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "src/ansiC.l"
; 
	YY_BREAK


case 8:
YY_RULE_SETUP
#line 56 "src/ansiC.l"
{BEGIN(LOOP);}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 57 "src/ansiC.l"
{line_num++;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "src/ansiC.l"
; 
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 64 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(CHAR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(CONST); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(DOUBLE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(FLOAT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(INT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(LONG); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(SHORT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(SIGNED); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(STATIC); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(UNSIGNED); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(VOID); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "src/ansiC.l"
{ count_bracket=0; BEGIN(DEF); printf("TYPE "); return(VOLATILE); }
	YY_BREAK

case 23:
YY_RULE_SETUP
#line 81 "src/ansiC.l"
{BEGIN(DEF_CMNT);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 82 "src/ansiC.l"
{printf("comment\n");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("IDENTIFIER "); 
						return(IDENTIFIER);
					}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 96 "src/ansiC.l"
{   struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("CONSTANT "); 
						return(CONSTANT); 
					}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "src/ansiC.l"
{   struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("CONSTANT ");
                        return(CONSTANT); 
                	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 117 "src/ansiC.l"
{ 		struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("CONSTANT ");
                        return(CONSTANT); 
                    }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 127 "src/ansiC.l"
{   struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("CONSTANT ");
                        return(CONSTANT); 
                    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 138 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("CONSTANT ");
                        return(CONSTANT); 
                    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 148 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("CONSTANT ");
                        return(CONSTANT); 
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 158 "src/ansiC.l"
{ 	struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("CONSTANT ");
                        return(CONSTANT); 
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 171 "src/ansiC.l"
{count_bracket++; printf("[ "); return('['); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 172 "src/ansiC.l"
{count_bracket--; printf("] "); return(']'); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 173 "src/ansiC.l"
{ return('&'); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 174 "src/ansiC.l"
{ return('!'); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 175 "src/ansiC.l"
{ return('~'); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 176 "src/ansiC.l"
{ return('-'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 177 "src/ansiC.l"
{ printf("+ "); return('+'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 178 "src/ansiC.l"
{ printf("* "); return('*'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 179 "src/ansiC.l"
{ return('/'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 180 "src/ansiC.l"
{ return('%'); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 181 "src/ansiC.l"
{ return('<'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 182 "src/ansiC.l"
{ return('>'); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 183 "src/ansiC.l"
{ return('^'); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 184 "src/ansiC.l"
{ return('|'); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 185 "src/ansiC.l"
{ BEGIN(INITIAL); printf("; "); return(';'); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 186 "src/ansiC.l"
{printf("= "); return('=');}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 187 "src/ansiC.l"
{printf(", "); return(',');}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 188 "src/ansiC.l"
{if(count_bracket==0) {BEGIN(INITIAL); printf("; "); return(';');} else { printf("{ "); return('{');}}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 189 "src/ansiC.l"
{if(count_bracket==0) {BEGIN(INITIAL); printf("; "); return(';');} else { printf("} "); return('}');}}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 190 "src/ansiC.l"
{printf(") "); return(')');}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 191 "src/ansiC.l"
{printf("( "); return('(');}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 193 "src/ansiC.l"
{ }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 194 "src/ansiC.l"
{ printf("%d\n",line_num); line_num++;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 195 "src/ansiC.l"
{if(count_bracket==0) {BEGIN(INITIAL); printf("; "); return(';');}}
	YY_BREAK


case 57:
YY_RULE_SETUP
#line 202 "src/ansiC.l"
{BEGIN(LOOP_CMNT);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 204 "src/ansiC.l"
{ printf("FOR "); return(FOR); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 206 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
										int len = strlen(yytext);
										s->string = malloc(sizeof(char)*(len+1));
										memcpy(s->string,yytext,sizeof(char)*(len+1));
										s->next = NULL;
										s->size = NULL;
										yylval.stringNode = s;
										printf("TYPE_OP "); 
										return(TYPE_OP);
									}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 217 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
										int len = strlen(yytext);
										s->string = malloc(sizeof(char)*(len+1));
										memcpy(s->string,yytext,sizeof(char)*(len+1));
										s->next = NULL;
										s->size = NULL;
										yylval.stringNode = s;
										printf("TYPE_OP "); 
										return(TYPE_OP);
									}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 227 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
										int len = strlen(yytext);
										s->string = malloc(sizeof(char)*(len+1));
										memcpy(s->string,yytext,sizeof(char)*(len+1));
										s->next = NULL;
										s->size = NULL;
										yylval.stringNode = s;
										printf("TYPE_OP "); 
										return(TYPE_OP);
									}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 237 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
										int len = strlen(yytext);
										s->string = malloc(sizeof(char)*(len+1));
										memcpy(s->string,yytext,sizeof(char)*(len+1));
										s->next = NULL;
										s->size = NULL;
										yylval.stringNode = s;
										printf("TYPE_OP "); 
										return(TYPE_OP);
									}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 247 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
										int len = strlen(yytext);
										s->string = malloc(sizeof(char)*(len+1));
										memcpy(s->string,yytext,sizeof(char)*(len+1));
										s->next = NULL;
										s->size = NULL;
										yylval.stringNode = s;
										printf("TYPE_OP "); 
										return(TYPE_OP);
									}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 258 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("IDENTIFIER "); 
						return(IDENTIFIER);
					}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 269 "src/ansiC.l"
{   struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
						printf("CONSTANT ");
						return(CONSTANT); 
					}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 279 "src/ansiC.l"
{   struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
                        printf("CONSTANT ");
						return(CONSTANT); 
                	}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 289 "src/ansiC.l"
{ 		struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
                        printf("CONSTANT ");
						return(CONSTANT); 
                    }
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 299 "src/ansiC.l"
{   struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
                        printf("CONSTANT ");
						return(CONSTANT); 
                    }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 310 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
                        printf("CONSTANT ");
						return(CONSTANT); 
                    }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 320 "src/ansiC.l"
{	struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
                        printf("CONSTANT ");
						return(CONSTANT); 
                        }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 330 "src/ansiC.l"
{ 	struct StringNode* s = malloc(sizeof(struct StringNode));
						int len = strlen(yytext);
						s->string = malloc(sizeof(char)*(len+1));
						memcpy(s->string,yytext,sizeof(char)*(len+1));
						s->next = NULL;
						s->size = NULL;
						yylval.stringNode = s;
                        printf("CONSTANT ");
						return(CONSTANT); 
                        }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 341 "src/ansiC.l"
{ printf("STRING ");
						return(STRING_LITERAL); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 344 "src/ansiC.l"
{		return(RIGHT_ASSIGN); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 345 "src/ansiC.l"
{ 		return(LEFT_ASSIGN); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 346 "src/ansiC.l"
{ 		return(ADD_ASSIGN); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 347 "src/ansiC.l"
{ 		return(SUB_ASSIGN); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 348 "src/ansiC.l"
{ 		return(MUL_ASSIGN); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 349 "src/ansiC.l"
{ 		return(DIV_ASSIGN); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 350 "src/ansiC.l"
{ 		return(MOD_ASSIGN); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 351 "src/ansiC.l"
{ 		return(AND_ASSIGN); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 352 "src/ansiC.l"
{ 		return(XOR_ASSIGN); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 353 "src/ansiC.l"
{ 		return(OR_ASSIGN); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 354 "src/ansiC.l"
{ 		return(RIGHT_OP); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 355 "src/ansiC.l"
{ 		return(LEFT_OP); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 356 "src/ansiC.l"
{ 		return(INC_OP); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 357 "src/ansiC.l"
{ 		return(DEC_OP); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 358 "src/ansiC.l"
{ 		return(PTR_OP); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 359 "src/ansiC.l"
{ 		return(AND_OP); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 360 "src/ansiC.l"
{ 		return(OR_OP); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 361 "src/ansiC.l"
{ 		return(LE_OP); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 362 "src/ansiC.l"
{ 		return(GE_OP); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 363 "src/ansiC.l"
{ 		return(EQ_OP); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 364 "src/ansiC.l"
{ 		return(NE_OP); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 365 "src/ansiC.l"
{ return(';'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 366 "src/ansiC.l"
{ return('{'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 367 "src/ansiC.l"
{ return('}'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 368 "src/ansiC.l"
{ return(','); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 369 "src/ansiC.l"
{ return(':'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 370 "src/ansiC.l"
{ return('='); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 371 "src/ansiC.l"
{ return('('); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 372 "src/ansiC.l"
{ return(')'); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 373 "src/ansiC.l"
{ return('['); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 374 "src/ansiC.l"
{ return(']'); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 375 "src/ansiC.l"
{ return('.'); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 376 "src/ansiC.l"
{ return('&'); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 377 "src/ansiC.l"
{ return('!'); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 378 "src/ansiC.l"
{ return('~'); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 379 "src/ansiC.l"
{ return('-'); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 380 "src/ansiC.l"
{ return('+'); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 381 "src/ansiC.l"
{ printf("* "); return('*'); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 382 "src/ansiC.l"
{ return('/'); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 383 "src/ansiC.l"
{ return('%'); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 384 "src/ansiC.l"
{ return('<'); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 385 "src/ansiC.l"
{ return('>'); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 386 "src/ansiC.l"
{ return('^'); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 387 "src/ansiC.l"
{ return('|'); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 388 "src/ansiC.l"
{ return('?'); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 391 "src/ansiC.l"
{BEGIN(INITIAL); end_num = line_num+1; printf("PARALLEL_END "); return(PARALLEL_END);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 393 "src/ansiC.l"
{printf("comment\n");}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 395 "src/ansiC.l"
{ }
	YY_BREAK
case 121:
/* rule 121 can match eol */
YY_RULE_SETUP
#line 396 "src/ansiC.l"
{ printf("%d\n",line_num); line_num++;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 397 "src/ansiC.l"
{ /* print error message */  }
	YY_BREAK

case 123:
YY_RULE_SETUP
#line 400 "src/ansiC.l"
{BEGIN(CMNT);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 401 "src/ansiC.l"
{printf("comment\n");}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 403 "src/ansiC.l"
{}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 404 "src/ansiC.l"
{}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 405 "src/ansiC.l"
{}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 407 "src/ansiC.l"
{}
	YY_BREAK
case 129:
/* rule 129 can match eol */
YY_RULE_SETUP
#line 409 "src/ansiC.l"
{ printf("%d\n",line_num); line_num++;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 410 "src/ansiC.l"
{ /* print error message */  }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 412 "src/ansiC.l"
ECHO;
	YY_BREAK
#line 2055 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CMNT):
case YY_STATE_EOF(DEF):
case YY_STATE_EOF(DEF_CMNT):
case YY_STATE_EOF(LOOP_CMNT):
case YY_STATE_EOF(LOOP):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 535 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 535 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 534);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 412 "src/ansiC.l"



yywrap()
{
	return(1);
}

